name "Sketchfab"
description "Klaas Nienhuis Scripts"
version 7copy "Foto klaas uitnodiging.jpg" to "$userScripts\KlaasTools\Sketchfab\"
copy "Foto klaas uitnodigingWeb.jpg" to "$userScripts\KlaasTools\Sketchfab\"
copy "IMG_9970_pasfoto.jpg" to "$userScripts\KlaasTools\Sketchfab\"
copy "IMG_9970_pasfoto_klein.jpg" to "$userScripts\KlaasTools\Sketchfab\"
copy "Submapje\Klaas_crop.jpg" to "$userScripts\KlaasTools\Sketchfab\Submapje\"
clear temp on MAX exit